### ISSUE TITLE
Nested resource controller

### ISSUE THREAD

**Issue by trinvh** [dwightwatson/bootstrap-form#100]
Is there any way to support nested resource controller when open a form?

Eg: ```Route::resource('users.books', 'UserBooksController')'```

**Comment by trinvh** [comment]
I found the answer by myself after reading the source code.
For anyone else meets the similar situation:

```{!! BootForm::open(['model' => $book, 'route' => ['users.books.store', $user]]) !!}```

**Comment by dwightwatson** [comment]
Glad you found it. Please let me know if you run into any other issues.
