### ISSUE TITLE
Input-group with prefix/suffix not working in vertical forms

### ISSUE THREAD

**Issue by flof** [dwightwatson/bootstrap-form#102]
When I add a input with a prefix or suffix addon to a vertical form, the addon is shown below the input. The problem is, that in vertical forms there gets no wrapper generated with the required class **input-group**, wich is neccessarry for input-groups with addons.

Screenshot:

<img width="740" alt="bootstrap-addon-issue-vertical" src="https://user-images.githubusercontent.com/1215125/34065148-6663316c-e1ff-11e7-8a75-a4f165e98b00.png">

Code:

```
<div class="panel panel-default">
    <div class="panel-body">
        {!! BootForm::vertical(['model' => $monitor, 'store' => 'ExampleController@store']) !!}
        {!! BootForm::text('name') !!}
        {!! BootForm::number('max_ping_interval', 'Ping interval', null, ['suffix' => BootForm::addonText('min')]) !!}
        {!! BootForm::checkbox('enabled') !!}
        {!! BootForm::submit('Create') !!}
        {!! BootForm::close() !!}
    </div>
</div>
```

**Comment by dwightwatson** [comment]
Closed by #103.
