### ISSUE TITLE
PUT method

### ISSUE THREAD

**Issue by AEK-BKF** [dwightwatson/bootstrap-form#111]
Hi,

I can't update my table without putting  the model.
Here my code line : 

`{!! BootForm::open(['update' => 'role.update', 'class' => 'validModal', 'id' => 'editRoleForm', '_method' => 'PUT']) !!}`

I want to get this code using your package : 

`<form method="PUT" action="{{ route('role.update', '') }}" class="validModal" id="editRoleForm">`

Thanks :)

**Comment by dwightwatson** [comment]
You have an underscore in front of the method key. Remove it.

**Comment by AEK-BKF** [comment]
Thank you so much :))))
