### ISSUE TITLE
Why we don't provide automatic visual feedback for required fields?

### ISSUE THREAD

**Issue by ricardovigatti** [dwightwatson/bootstrap-form#112]
```
{!! BootForm::text('firstname', 'Firstname', null, ['required']) !!}
```

If the "required" attribute is being used, can we just provide a visual feedback appended to the label?

Something like: ```<span class="required">*</span>```

**Comment by dwightwatson** [comment]
Not likely to implement this in this package sorry, I think adding an asterisk is a specific use case. You might be able to insert an asterisk using CSS if you target required inputs.

**Comment by ricardovigatti** [comment]
Yes, you're right. Thanks anyway.
