### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by krebbi** [dwightwatson/bootstrap-form#115]
Hi,

what do you think about an Autocomplete value as optional argument?

**Comment by dwightwatson** [comment]
As an optional argument that does what?

Generally an autocomplete is going to be its own component controlled by client-side code. 

This package is just a simple HTML builder for form elements. I don’t see autocomplete being a good fit here unless I’m misunderstanding the suggestion.

**Comment by krebbi** [comment]
setting the autocomplete value? see attached screenshot.

working with your extension is really a charme! I'm complaining on a high level. ;-) 

![bildschirmfoto 2018-05-03 um 01 02 23](https://user-images.githubusercontent.com/3884521/39553376-b28e71fc-4e6d-11e8-92ff-9986b2d031d3.png)

**Comment by krebbi** [comment]
Yes, you're right. Passing this via your Options Array works. 
Just thought because of its increasing importance it should be its own option. 
Up to you. ;-)

**Comment by dwightwatson** [comment]
That's quite interesting, seems like this warning was introduced in Chrome a while ago. It's odd that I've never seen it, wonder what triggers it.

I'm not sure it's appropriate to make `autocomplete` a direct argument for the inputs. I don't think it would be clear to other developers who read the code what the intention is. I think it's clearer to just pass it in as an option, and it's not that much extra code.

If it's something you really wanted for your project it shouldn't be too hard to extend the form builder and make it a top-level argument as you need. But yeah, for now I think it's best to use the options field. Thanks for bringing this up though.
