### ISSUE TITLE
.Standard Forms

### ISSUE THREAD

**Issue by jpsmith1981** [dwightwatson/bootstrap-form#12]
Hey man this is awesome!  However  I can not seem to render a standard form....

Doing this in my blade template:

`
{{ BootstrapForm::openStandard()}}
{{BootstrapForm::text('username')}}
{{ BootstrapForm::submit('Login') }}
{{ Form::close() }}
`

Produces the fields like:
`
<div class="form-group">
    <label for="username" class="control-label col-md-2">Username</label>
    <div class="col-md-10">
           <input class="form-control" name="username" type="text">
    </div>
</div>
`

The expected result would have been 
`
 <div class="form-group">
    <label for="username">Username</label>
    <input type="text" class="form-control" id="username" placeholder="Username">
  </div>
`

**Comment by dwightwatson** [comment]
Hey sorry for the delay getting back to you, I've been having a bit of trouble with my Homestead setup. Are you able to paste the exact output you're getting when using the standard form code above?

**Comment by opheliadesign** [comment]
Any progress on this? Just ran into this issue, really need the full width of a textarea in its parent column for Redactor.

**Comment by dwightwatson** [comment]
Unfortunately it's going to take a little more work than expected to get this working as expected - when I built this it was heavily favoured towards horizontal forms. I would love to do a complete rewrite but I just don't have time at the moment. Like I said earlier, happy to accept any pull requests that implement the desired behaviour.

**Comment by SystemF** [comment]
This issue is fixed after the latest merge

**Comment by dwightwatson** [comment]
Thanks to @SystemF this is now fixed in release `0.9.6`.
