### ISSUE TITLE
redirect()->back() after failed validation not preserving empty values

### ISSUE THREAD

**Issue by ricardovigatti** [dwightwatson/bootstrap-form#120]
I don't know if this is the expected behavior or what, but seems odd to me:

Let me know if anyone can reproduce this.

 - When updating an already registered record

 - The Model has a field with required validation

 - Submit the form with this field empty

 - Validate at controller and redirect back with old inputs

 - The field now should be empty, with error messages. It have the error messages, but its filled with the registered value from database.

```php
// myController

$model->save($request->all());
if ($model->isInvalid()) {
      return redirect()->back()->withInput()->withErrors();
}
```

```html
// myView

{!! BootForm::open(['model' => $model, 'update' => 'admin.models.update']); !!}
{!! BootForm::text('field', 'myField') !!}
```

To add some information, the old value is filled normally after validation IF it's not empty, like when we are validating string length.

**Comment by ricardovigatti** [comment]
I will try again within a clean install, soon

**Comment by dwightwatson** [comment]
Doesn't sound quite right - I would have thought the empty string from the previous request would take precedence over the current value of the model attribute. However this may be an issue with [laravelcollective/html](https://github.com/LaravelCollective/html) - the form builder we use under the hood. See if you can replicate your issue on a clean install using their form builder directly, or using this package.

**Comment by ricardovigatti** [comment]
Maaaan, this issue gave me a looot of work! And u can keep cool cause it wasn't a problem with this package.

For some reason, that i don't understand, my **package.lock** file was defining an alias from "laravie/html" to "laravelcollective/html". I had to delete and generate again my package.lock file.

Thanks for your attention.

**Comment by dwightwatson** [comment]
Glad to hear you got to the bottom of it, and thanks for letting me know.
