### ISSUE TITLE
Html dependencie version

### ISSUE THREAD

**Issue by giovannefc** [dwightwatson/bootstrap-form#13]
Hi,
Composer returns this error:
Problem 1
    - watson/bootstrap-form 0.8.5 requires illuminate/html 4.* -> no matching package found.

The Html package version is 5.0.x.

Thank you.

**Comment by dwightwatson** [comment]
Pull in `0.9.*` for Laravel 5. Apologies, I'm working on a complete rebuild for the new Laravel.
