### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by vedmant** [dwightwatson/bootstrap-form#137]
With PHP 8 it shows following error:

```
 Required parameter $wrapperElement follows optional parameter $name

  at vendor/watson/bootstrap-form/src/BootstrapForm.php:830
    826▕      * @param  string  $label
    827▕      * @param  string  $element
    828▕      * @return string
    829▕      */
  ➜ 830▕     public function getFormGroup($name = null, $label = null, $wrapperElement)
    831▕     {
    832▕         if (is_null($label)) {
    833▕             return $this->getFormGroupWithoutLabel($name, $wrapperElement);
    834▕         }

```

**Comment by dwightwatson** [comment]
Thanks for this. It looks like this will require a major version change as we'd have to rethink method signatures to make them compatible. 

Unfortunately I don't use this package anymore and don't have the time or motivation to bring it up to speed. I'd suggest forking to make it work for your use-case or find alternatives.

**Comment by vedmant** [comment]
@dwightwatson Generally just this fixes it:

```
    public function getFormGroup($name = null, $label = null, $wrapperElement = null)
```

**Comment by dwightwatson** [comment]
Is that the only change required to get it working? If so I'd be happy to accept a PR and tag it.

**Comment by vedmant** [comment]
@dwightwatson Sure, I'll double check and add PR a bit later

**Comment by dwightwatson** [comment]
Hang on - I think you're using an older version of the package.

The method signature in the master branch is different to the one you linked above: https://github.com/dwightwatson/bootstrap-form/blob/master/src/BootstrapForm.php#L603-L613

It appears I added PHP 8.0 support earlier in the year.

Please make sure you're running the latest version of the package.

**Comment by vedmant** [comment]
@dwightwatson I was using the lates available on packagist 2.1.0, this is what's installed with `composer require watson/bootstrap-form`

**Comment by dwightwatson** [comment]
Hmm... looks like perhaps it was never tagged. Does `dev-master` work for you?

**Comment by vedmant** [comment]
@dwightwatson I didn't try dev-master, I just moved package to the app and make edits for now
