### ISSUE TITLE
Laravel 5 Service Provider 

### ISSUE THREAD

**Issue by davidpiesse** [dwightwatson/bootstrap-form#14]
$this->package('watson/bootstrap-form', null, __DIR__);
This no longer works with the release of L5.

Lots of other packages have the same issue with the deprecation of package().

**Comment by dwightwatson** [comment]
I've been working on a rewrite for Laravel 5 but haven't been able to give as much time to it as I would have liked.

If you'd like to make a PR that fixes the issue with `package()` though I'll be more than happy to bring it in and tag it.

**Comment by davidpiesse** [comment]
I'll see what I can do.

Cheers,
David

**Comment by dwightwatson** [comment]
@martynling was good enough to make PR #15 which brings Laravel 5 compatibility.
