### ISSUE TITLE
The 'Submit' button on horizontal forms doesn't align with the input fields.

### ISSUE THREAD

**Issue by davechez** [dwightwatson/bootstrap-form#20]
On 99% of forms I see, the submit button is aligned with the input fields if it is a horizontal form. Currently the submit button is just left aligned. I think it would be a simple change that would make the forms much better looking.

**Comment by msieprawski** [comment]
I can agree with @davechez.
Simple code example:
```
{!! BootstrapForm::openHorizontal() !!}
{!! BootstrapForm::text('name') !!}
{!! BootstrapForm::submit('Save changes') !!}
{!! BootstrapForm::close() !!}
```

**Comment by opheliadesign** [comment]
Agreed. This plus the issue of openStandard resulting in the form still being horizontal (minus the `form-horizontal` class in the form element) may be a deal breaker for me. :/

**Comment by dwightwatson** [comment]
Totally agree here, unfortunately I don't have time to implement this at the moment. Happy to accept any pulls in the meantime.

**Comment by dwightwatson** [comment]
This should now be fixed on `dev-master`. You'll probably want to publish the new configuration file that allows you to configure the offset for the button. I'm hoping to tag this in a `1.0.0` release soon.
