### ISSUE TITLE
Change horizontal input size on the fly

### ISSUE THREAD

**Issue by opheliadesign** [dwightwatson/bootstrap-form#24]
Is there any way to change the col span for an input within the view? For example, if col-lg-8 is set in the settings, add a col-lg-4 directly on the page.

**Comment by dwightwatson** [comment]
You can now pass `left_column_class`, `'left_column_offset_class' and `right_column_class` as options to change the input sizes for a single form on `dev-master`. Be sure to pull in the new configuration file. I'd like to tag this in a `1.0.0` release soon.
