### ISSUE TITLE
Check if model should be used, causes MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by gijsbeijer** [dwightwatson/bootstrap-form#26]
in "Bootstrapform.php" in the open function is a check on $options['model'], if this exists then the (protected) model function wil be used. 

In the model function is another check on model but this will have no effect because it would'nt  go in there in the first place if no model is passed. If it doesn't go in there it wont take the $options['store'] and will give the url of the current page as a default. This will result in POSTing to the /create page wich will throw the MethodNotAllowedHttpException error.

So either the check if model is set schould be in the open method firing either $this->form->open() or the model function, OR the model function should be public, this way it would make sense that the check is done twice.

**Comment by dwightwatson** [comment]
I'm not sure I follow, there are two different checks. The check in `open` is checking to see if a model has been passed. The check in the `model` method is then checking if the `exists` property is true or false on the model, as that indicates whether the model has already been persisted, so we know whether to use the `store` or `update` method.

**Comment by gijsbeijer** [comment]
well the documentation states that if you want to use a store method you can also pass a NULL value, this won't get past the isset(). so it will use the form open, wich does not take the store option as an action for the form, so it reverts to the current URL.

my quickfix in the "open" method:

    if (isset($options['model'])) {
        return $this->model($options);
        } else {
            // Otherwise, we're storing a brand new model using the POST method.
            $route = Str::contains($options['store'], '@') ? 'action' : 'route';

            $options[$route] = $options['store'];
            $options['method'] = 'POST';
        }

**Comment by dwightwatson** [comment]
Oh okay, I see what you mean. Originally the documentation indicated that you would always pass a model instance (either a persisted model or a fresh instance) to the `model` key. I'll work on a fix that won't break it for people not using the form models.

**Comment by dwightwatson** [comment]
I've just pushed and tagged a fix that will handle the `model` key being `null` so that it can fall back to the store route. Thanks for finding this :smile:

**Comment by gijsbeijer** [comment]
you're welcome, i'll update right away :)
