### ISSUE TITLE
Multiple checkboxes, select options not working

### ISSUE THREAD

**Issue by opheliadesign** [dwightwatson/bootstrap-form#31]
Hello,

I am trying to check checkboxes on my form based on results from a table. The results are presented as an array of integers (the IDs of categories that a member belongs to). 

Following the instructions, I provide the checkbox options as an array of id => text. When I pass an array of selected IDs (values) - `[1, 2]`, every checkbox is marked as Selected. How can I prevent this?
```
{!! BootstrapForm::checkboxes('categories[]', 'Categories:', $categories, isset($memberCategories) ? $memberCategories : null) !!}
```

**Comment by opheliadesign** [comment]
Just solved the problem - a `belongsTo` relation on the model passed to the form appears to have caused this, I changed from `categories[]` to `types[]` and the problem went away.

**Comment by dwightwatson** [comment]
Awesome, thanks for posting the solution too!
