### ISSUE TITLE
Validate checkboxes array

### ISSUE THREAD

**Issue by SystemF** [dwightwatson/bootstrap-form#36]
Hi Dwight,

I ran in to a problem. I've created a checkboxes collection. The checkboxes have the name attribute called websites[] (as an array).

I've created a new request for validation. When I validate the form input for the name websites (without array brackets) it works like a charm, validation fails when empty, but I don't get the error message. When I validate for the name websites[] it will never pass validation but I get the error message.

Hope you'll understand. Do you have any idea how to validate checkboxes the right way?

Regards, Ferry!

**Comment by dwightwatson** [comment]
That's an interesting issue, it sounds as though we should be stripping `[]` from the field name when fetching the errors for the field [in this method](https://github.com/dwightwatson/bootstrap-form/blob/master/src/BootstrapForm.php#L756-L767). Does this sound right to you?

**Comment by SystemF** [comment]
Yep, I think that is the solution. I will test some things.
Op 18 sep. 2015 2:57 AM schreef "Dwight Watson" <notifications@github.com>:

**Comment by dwightwatson** [comment]
Let me know how you go with it, happy to push this out and tag it or accept a PR if you've got one.

**Comment by dwightwatson** [comment]
Fixed by #37 (thanks!)
