### ISSUE TITLE
form errors are not displayed when using (multidemensional)array-fieldnames

### ISSUE THREAD

**Issue by gijsbeijer** [dwightwatson/bootstrap-form#40]
If i'm using fieldnames like: 'product_variation[8][img]', form errors wil not display.

Laravel is using dot-notation for checking and displaying errors, so the error values for the input above should be retrieved using product_variation.8.img.

The following code should resolve this
```
protected function getFieldError($field, $format = '<span class="help-block">:message</span>')
{
    $field = str_replace('[]','', $field);
    $field = str_replace('][', '.', $field);
    $field = str_replace('[', '.', $field);
    $field = str_replace(']', '', $field);

    if ($this->getErrors()) {
        $allErrors = $this->config->get('bootstrap_form.show_all_errors');

        if ($allErrors) {
            return implode('', $this->getErrors()->get($field), $format);
        }

        return $this->getErrors()->first($field), $format);
    }
}
```

**Comment by dwightwatson** [comment]
I really wasn't keen on using that many `str_replace` calls so I refactored with a regex which I think will do the trick. Tagged version `1.0.8`.

**Comment by gijsbeijer** [comment]
You're right, that's way better. was a bit of a quickfix for me :p
