### ISSUE TITLE
Default 0 optgroup on select method.

### ISSUE THREAD

**Issue by ifaniqbal** [dwightwatson/bootstrap-form#41]
If I try this:

    {!! BootstrapForm::select('name', 'Label', [$list]) !!}

Why do I get the options tag wrapped by optgroup like this:

    <optgroup label="0">
        <option>...</option>
    </optgroup>

**Comment by dwightwatson** [comment]
Because you're passing `$list` inside an array? I think that's the way the underlying form builder interprets arrays... as option groups. Remove the array braces and you should be alright.

    {!! BootstrapForm::select('name', 'Label', $list) !!}

**Comment by ifaniqbal** [comment]
Awesome
