### ISSUE TITLE
Any way to handle nested resources?

### ISSUE THREAD

**Issue by DODMax** [dwightwatson/bootstrap-form#43]
Hi,

I'm trying to get nested resource controller to work but can't figure in out.
Usually I would do `Form::open(array('action' => array('Controller@method', $user->id)))`

However because BootstrapForm->model() is using Str::contains (line 146) to chose between route and action I cannot use such array.

Is there any other way to use an action with a nested resource?

Thanks

**Comment by DODMax** [comment]
I realize this is actually handled in https://github.com/dwightwatson/bootstrap-form/pull/30

Although I would simply do:
```
$update = is_array($options['update']) ? $options['update'][0] : $options['update'];
$route = Str::contains($update, '@') ? 'action' : 'route';
```

**Comment by dwightwatson** [comment]
Hey, unfortunately there isn't currently a good solution for handling nested resources. Haven't had a chance to look into this properly, but it is an issue.
