### ISSUE TITLE
Laravel 5.2 support

### ISSUE THREAD

**Issue by Febalist** [dwightwatson/bootstrap-form#44]
Please add Laravel 5.2 support.
Now it is a fatal error `Call to undefined method Illuminate\Foundation\Application::bindShared()`.
From [Laravel upgrade guide](https://laravel.com/docs/upgrade#upgrade-5.1.0):
> The following Laravel features have been deprecated and will be removed entirely with the release of Laravel 5.2 in December 2015:
> ...
> * The service container's **bindShared** method has been deprecated in favor of the singleton method.

**Comment by Febalist** [comment]
I did [pull request](https://github.com/dwightwatson/bootstrap-form/pull/45) to resolve the issue.

**Comment by dwightwatson** [comment]
Handled by #45.
