### ISSUE TITLE
Append id to inputs for label correct association

### ISSUE THREAD

**Issue by sputinyk** [dwightwatson/bootstrap-form#47]
```
{!!BootForm::text('foo', 'Foo')!!}
```
Generates
```
<div class="form-group ">
    <label for="foo" class="control-label">Foo</label>
    <div>
        <input class="form-control" name="foo" type="text">
    </div>
</div>
```

I think the id attribute must be set, like this:
<pre>
&lt;div class="form-group "&gt;
    &lt;label for="foo" class="control-label"&gt;Foo&lt;/label&gt;
    &lt;div&gt;
        &lt;input class="form-control" name="foo" type="text" <b>id="foo"</b>&gt;
    &lt;/div&gt;
&lt;/div&gt;
<pre>

**Comment by dwightwatson** [comment]
Wow, good catch! Can't believe that wasn't working. Fixing that now...

**Comment by dwightwatson** [comment]
Tagged in release `1.0.10`.
