### ISSUE TITLE
Checkboxes rendered wrong

### ISSUE THREAD

**Issue by ps91** [dwightwatson/bootstrap-form#52]
The "checkboxes" option isn't rendering the right way. The "name" attribute should be set in a way of creating an array of options when sending the data to the controller. But this isn't happening. (At least not with the example you show in your home page). So something like this:

{!! BootForm::checkboxes('colors', 'Colors*', $colors, null, ["required"]) !!}

Is rendering like this:
```
<div>
    <label class="checkbox-inline">
       <input type="checkbox" value="1" name="colors">
       Yellow
   </label>
   <label class="checkbox-inline">
       <input type="checkbox" value="2" name="colors">
       Green
   </label>
</div>
```

Shouldn't it be rendering like this?
```
<div>
    <label class="checkbox-inline">
       <input type="checkbox" value="1" name="colors[]">
       Yellow
   </label>
   <label class="checkbox-inline">
       <input type="checkbox" value="2" name="colors[]">
       Green
   </label>
</div>
```

So I could access it from the controller as an array? Or there's is another way of accessing this data the way it's rendering?

**Comment by dwightwatson** [comment]
Sorted in #53. Will tag a release in a second.

It looks like it's doubling up on the `<label class="checkbox-inline">` too - is that just a mistake in your example or is that being generated incorrectly too?

**Comment by ps91** [comment]
It was a copy and past mistake. Already edited my comment.

**Comment by dwightwatson** [comment]
I've rolled this one back, it was a breaking change for people who were already suffixing their own `[]`. It also forced people to use checkboxes when they might not want to, for whatever reason.

I've updated the docs to indicate that you should supply your own `[]` if that's what you're after. Sorry about reversing on this one, but thanks for taking the time to put this together.
