### ISSUE TITLE
Undefined index: help_text

### ISSUE THREAD

**Issue by andycaramba** [dwightwatson/bootstrap-form#57]
Hi. After [this commit](https://github.com/dwightwatson/bootstrap-form/commit/a0d5e841df1b86605e2598c608e82f2c204be56e) I have an error `Undefined index: help_text` in
```php
protected function getHelpText($field, array $options = [])
{
    if (array_key_exists($options['help_text'])) {
        return '<span class="help-block">' . e($options['help_text']) . '</span>';
    }
    ...
```

**Comment by andycaramba** [comment]
It should be `array_key_exists('help_text', $options)` here

**Comment by dwightwatson** [comment]
Sorry about this and for taking so long to resolve it, was on an international flight. I've just tagged a new version that should fix this. I really need to get the test coverage up.
