### ISSUE TITLE
Unable to hide label

### ISSUE THREAD

**Issue by jilenloa** [dwightwatson/bootstrap-form#69]
calling BootForm::text($name, false) does not hide label.

**Comment by Mochaka** [comment]
I'm getting the same issue

**Comment by dwightwatson** [comment]
Hey, thanks for reporting this. I'm currently away from a computer and will be for another week or so. If someone could put together a PR it would be much appreciated, otherwise you can lock onto a previous release until this is fixed.

**Comment by arredgroup** [comment]
Hi, I have the same issue...

**Comment by dwightwatson** [comment]
This should be fixed in `1.0.18`. 

Please let me know if you run into any other issues.
