### ISSUE TITLE
https://github.com/elkarimareda/bootstrap-form

### ISSUE THREAD

**Issue by elkarimareda** [dwightwatson/bootstrap-form#73]
I have a solution to remove the html escape on blade template like that {{BootForm::text('name')}}

**Comment by elkarimareda** [comment]
https://github.com/elkarimareda/bootstrap-form

**Comment by dwightwatson** [comment]
Hey, yeah `HtmlString` would do the trick but I believe it was only introduced in Laravel 5.3, while this package is compatible with 5.0+. Would definitely be something I'd like to look at in the next major release of the package.
