### ISSUE TITLE
labels on submit buttons

### ISSUE THREAD

**Issue by jwynharris** [dwightwatson/bootstrap-form#74]
Happy new year!

Just noticed a change in behaviour from 1.0.17 and 1.0.19 due to a refactor. In 1.0.19 you now check for non null label string (previously it checking for false). The problem is that for submit you pass in false (rather than null) meaning empty labels are always created above submit buttons which isn't desirable!

Hopefully an easy fix? Just need to pass in null (instead of false) for getFormGroup() for submit, button and radio.

Cheers,
Jeremy

**Comment by dwightwatson** [comment]
Hey Jeremy - thanks for reporting this. I've just pushed a change to `master` that should fix this, if you have a chance please give it a test and see if it sorts it out for you. If it's all good I'll tag a new release.

**Comment by jwynharris** [comment]
Yup - all good! Thank you! Jeremy

**Comment by dwightwatson** [comment]
Cool, tagged release `1.0.20.`
