### ISSUE TITLE
Checkbox - ability to remove first label

### ISSUE THREAD

**Issue by MichaelHoughton** [dwightwatson/bootstrap-form#75]
Thanks for your awesome work on this - it has been a huge time saver.

I notice that when using:

```php
echo BootForm::checkbox('new', 'This product is new', null, null, ['inline' => false]);
echo BootForm::checkbox('coming_soon', 'This product is coming soon');
```

It generates two labels - for example:
![screenshot from 2017-01-09 17 35 33](https://cloud.githubusercontent.com/assets/5341149/21776394/1a39ab5a-d692-11e6-8c51-e5b5b4687795.png)

I just wanted to see, if it was possible for the first label NOT to generate.

Please let me know - I will be happy to work on a PR for this if you think it would be a good feature.

**Comment by dwightwatson** [comment]
Thanks so much! I don't think this is possible at the moment, but I'd be happy to accept a PR that implements it. 

Looking at your examples it's actually a bit silly that we have two labels. I'd be inclined to actually not show the first label at all. What do you think?

**Comment by MichaelHoughton** [comment]
Hey @dwightwatson - I would definitely agree - and I will be happy to work on a PR for this.  I will let you know when it is ready!

**Comment by MichaelHoughton** [comment]
Hey @dwightwatson - this is done - the PR is here:
https://github.com/dwightwatson/bootstrap-form/pull/76

I will be happy to continue to help improve this - as well as write some more specific tests.  Please feel free to assign any issues to me, if you need help getting them completed - I know it can be hard to find the time!
