### ISSUE TITLE
Passing null to label attribute is causing an error in the label

### ISSUE THREAD

**Issue by MichaelHoughton** [dwightwatson/bootstrap-form#77]
If the following is entered in:

```php
echo BootForm::text('meta_description', null);
```

It outputs the label as:
"Meta_Description"

Rather than "Meta Description"

Please feel free to assign this issue to me and I will solve it.

**Comment by dwightwatson** [comment]
Sounds like `Str::title` just capitalises the start of each word. Not what I expected. Unless you can think of a better solution, maybe it should just replace any underscores with spaces as well?

**Comment by MichaelHoughton** [comment]
Replacing underscores with spaces is exactly the first that will be required here :)

**Comment by dwightwatson** [comment]
Ah sorry, just saw your edit. I just pushed the change through as I still had the code open in Sublime.

**Comment by MichaelHoughton** [comment]
No problem - that's why I wanted to ask first - just incase you were already one it!  And perfect fix too - thanks for this!
