### ISSUE TITLE
Planning for Bootstrap 4

### ISSUE THREAD

**Issue by SystemF** [dwightwatson/bootstrap-form#92]
Hi Dwight,

Are you planning a update for Bootstrap 4?

Cheers, Ferry!

**Comment by dwightwatson** [comment]
To be honest, not really. I don't use this library myself anymore and I'm slowly working Laravel Collective's Form builder out of my apps as well. I'm happy to accept any PRs that add support for it but I'm not sure I'll get to it myself. 

Might be worth waiting until a bit later in the Bootstrap release cycle as well, as there have been quite a number of breaking changes through the alphas/betas.

**Comment by SystemF** [comment]
Can I ask how you manage your forms nowadays? Plain html in the views?

**Comment by dwightwatson** [comment]
Yeah, been moving toward just plain HTML, with a couple of macros for displaying errors.

I like to stay as close as possible to "the Laravel way" of doing things, and seeing as Taylor removed the form builder from the core and now that the work on the form builder appears to have slowed down I felt it was better to follow that path.

**Comment by SystemF** [comment]
Thanks for your reply, appreciate it! You've made me think! :)
