### ISSUE TITLE
Auto-discover for Laravel 5.5

### ISSUE THREAD

**Issue by vedmant** [dwightwatson/bootstrap-form#99]
It would be nice to add auto-discover configuration for Laravel 5.5, will need in composer file:

    "extra": {
        "laravel": {
            "providers": [
                "Watson\\BootstrapForm\\BootstrapFormServiceProvider"
            ],
            "aliases": {
                "BootForm": "Watson\\BootstrapForm\\Facades\\BootstrapForm"
            }
        }
    }

**Comment by dwightwatson** [comment]
Great suggestion - all done.
